"""Fixed typo in DatasetFile

Revision ID: 0fbe86846c35
Revises: a762c964081a
Create Date: 2019-09-09 00:48:59.969857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbe86846c35'
down_revision = 'a762c964081a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
