"""Added mask information for each file

Revision ID: 838597d26d59
Revises: cccf70b6944b
Create Date: 2019-09-16 15:01:44.263413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838597d26d59'
down_revision = 'cccf70b6944b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('mask_dir', sa.String(), nullable=True))
    op.add_column('datasetfile', sa.Column('mask', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasetfile', 'mask')
    op.drop_column('dataset', 'mask_dir')
    # ### end Alembic commands ###
