"""Added columns

Revision ID: 93feed8b3057
Revises: 0fbe86846c35
Create Date: 2019-09-15 21:42:34.238744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93feed8b3057'
down_revision = '0fbe86846c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysismodel', sa.Column('index', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysismodel', 'index')
    # ### end Alembic commands ###
