"""Added datasetfile table

Revision ID: a762c964081a
Revises: 05c784737cdf
Create Date: 2019-09-09 00:35:31.607060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a762c964081a'
down_revision = '05c784737cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysismodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysismodel_dataset_id'), 'analysismodel', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analysismodel_id'), 'analysismodel', ['id'], unique=False)
    op.create_index(op.f('ix_analysismodel_name'), 'analysismodel', ['name'], unique=False)
    op.create_table('datasetfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasetfile_dataset_id'), 'datasetfile', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_datasetfile_id'), 'datasetfile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasetfile_id'), table_name='datasetfile')
    op.drop_index(op.f('ix_datasetfile_dataset_id'), table_name='datasetfile')
    op.drop_table('datasetfile')
    op.drop_index(op.f('ix_analysismodel_name'), table_name='analysismodel')
    op.drop_index(op.f('ix_analysismodel_id'), table_name='analysismodel')
    op.drop_index(op.f('ix_analysismodel_dataset_id'), table_name='analysismodel')
    op.drop_table('analysismodel')
    # ### end Alembic commands ###
