"""Added meta information for each file

Revision ID: cccf70b6944b
Revises: 93feed8b3057
Create Date: 2019-09-16 00:08:20.988470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccf70b6944b'
down_revision = '93feed8b3057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasetfile', sa.Column('meta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasetfile', 'meta')
    # ### end Alembic commands ###
